name: Clipboard Builds

on: [ push, pull_request ]
jobs:
  linux_x11_wayland:
    strategy:
      fail-fast: false
      matrix:
        gcc: [ 10, 11, 12 ]
        arch: [ i386, amd64, arm64, riscv64, armhf, ppc64el, s390x ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          GPP_PACKAGE=""
          GPP_NAME="g++"
          if [[ "${{ matrix.arch }}" == "i386" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-i686-linux-gnu"
            GPP_NAME="i686-linux-gnu-g++-${{ matrix.gcc }}"
          fi
          
          if [[ "${{ matrix.arch }}" == "amd64" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}"
            GPP_NAME="x86_64-linux-gnu-g++-${{ matrix.gcc }}"
          fi

          if [[ "${{ matrix.arch }}" == "arm64" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-aarch64-linux-gnu"
            GPP_NAME="aarch64-linux-gnu-g++-${{ matrix.gcc }}"
            # add arm64 architecture from Ubuntu ports
            sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ jammy-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ jammy-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ jammy-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi

          if [[ "${{ matrix.arch }}" == "riscv64" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-riscv64-linux-gnu"
            GPP_NAME="riscv64-linux-gnu-g++-${{ matrix.gcc }}"
            # add riscv64 architecture from Ubuntu ports
            sudo echo "deb [arch=riscv64] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=riscv64] http://ports.ubuntu.com/ jammy-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=riscv64] http://ports.ubuntu.com/ jammy-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=riscv64] http://ports.ubuntu.com/ jammy-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi

          if [[ "${{ matrix.arch }}" == "armhf" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-arm-linux-gnueabihf"
            GPP_NAME="arm-linux-gnueabihf-g++-${{ matrix.gcc }}"
            # add armhf architecture from Ubuntu ports
            sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ jammy-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ jammy-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ jammy-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi

          if [[ "${{ matrix.arch }}" == "ppc64el" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-powerpc64le-linux-gnu"
            GPP_NAME="powerpc64le-linux-gnu-g++-${{ matrix.gcc }}"
            # add ppc64el architecture from Ubuntu ports
            sudo echo "deb [arch=ppc64el] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=ppc64el] http://ports.ubuntu.com/ jammy-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=ppc64el] http://ports.ubuntu.com/ jammy-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=ppc64el] http://ports.ubuntu.com/ jammy-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi

          if [[ "${{ matrix.arch }}" == "s390x" ]]
          then
            GPP_PACKAGE="g++-${{ matrix.gcc }}-s390x-linux-gnu"
            GPP_NAME="s390x-linux-gnu-g++-${{ matrix.gcc }}"
            # add s390x architecture from Ubuntu ports
            sudo echo "deb [arch=s390x] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=s390x] http://ports.ubuntu.com/ jammy-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=s390x] http://ports.ubuntu.com/ jammy-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=s390x] http://ports.ubuntu.com/ jammy-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi
          
          # This limits apt to only looking or amd64 and i386 from Azure, see https://github.com/actions/virtual-environments/issues/1961
          sudo sed -i'' -E 's/^deb http:\/\/(azure.archive|security).ubuntu.com/deb [arch=amd64,i386] http:\/\/\1.ubuntu.com/' /etc/apt/sources.list

          sudo dpkg --add-architecture "${{ matrix.arch }}"
          sudo apt-get update
          sudo apt-get install -y \
            "${GPP_PACKAGE}" \
            "libx11-dev:${{ matrix.arch }}" \
            "libwayland-dev:${{ matrix.arch }}"
          
          cd build
          
          cmake .. \
            "-DCMAKE_CXX_COMPILER=${GPP_NAME}" \
            "-DCMAKE_BUILD_TYPE=MinSizeRel"
          
          cmake --build . -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-linux-gcc${{ matrix.gcc }}-${{ matrix.arch }}
          path: build/output
  macos-arm64-amd64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build . -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-macos-arm64-amd64
          path: build/output
  windows-amd64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build . --config Release -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-windows-amd64
          path: build/output
  windows-arm64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=ARM64
          cmake --build . --config Release -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-windows-arm64
          path: build/output
  freebsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            sudo pkg install -y cmake gcc12
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DNO_X11=1 -DCMAKE_CXX_COMPILER=g++12
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-freebsd-amd64
          path: build/output
  openbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.2'
          shell: bash
          run: |
            sudo pkg_add cmake g++-11.2.0p3
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DNO_X11=1 -DCMAKE_CXX_COMPILER=eg++
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-openbsd-amd64
          path: build/output
  openbsd-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: openbsd
          architecture: arm64
          version: '7.2'
          shell: bash
          run: |
            sudo pkg_add cmake g++-11.2.0p3
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DNO_X11=1 -DCMAKE_CXX_COMPILER=eg++
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-openbsd-arm64
          path: build/output
  netbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: netbsd
          architecture: x86_64
          version: '9.2'
          shell: bash
          run: |
            sudo pkgin install -y cmake gcc12
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_COMPILER=/usr/pkg/gcc12/bin/g++
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-netbsd-amd64
          path: build/output