name: Clipboard Tests

on: [ push, pull_request ]
jobs:
  test-linux-gcc:

    strategy:
      fail-fast: false
      matrix:
        os: [ 20.04, 22.04 ]
        gcc: [ 10, 11, 12 ]
        x11: [ "1", "0" ]
        wayland: [ "1", "0" ]
        arch: [ i386, amd64 ]
        exclude:
          - os: 20.04
            gcc: 12
          - os: 20.04
            arch: i386
            gcc: 11

    runs-on: ubuntu-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          NO_X11=1
          NO_WAYLAND=1
          PACKAGES=""
          GPP_NAME="g++"
          
          if [[ "${{ matrix.x11 }}" == "1" ]]
          then
            NO_X11=0
            PACKAGES="${PACKAGES} libx11-dev:${{ matrix.arch }}"
          fi
          
          if [[ "${{ matrix.wayland }}" == "1" ]]
          then
            NO_WAYLAND=0
            PACKAGES="${PACKAGES} libwayland-dev:${{ matrix.arch }}"
          fi
          
          if [[ "${{ matrix.arch }}" == "i386" ]]
          then
            PACKAGES="${PACKAGES} g++-${{ matrix.gcc }}-i686-linux-gnu"
            GPP_NAME="i686-linux-gnu-g++-${{ matrix.gcc }}"
          fi
          
          if [[ "${{ matrix.arch }}" == "amd64" ]]
          then
            PACKAGES="${PACKAGES} g++-${{ matrix.gcc }}"
            GPP_NAME="x86_64-linux-gnu-g++-${{ matrix.gcc }}"
          fi
          
          sudo dpkg --add-architecture "${{ matrix.arch }}"
          sudo apt-get update
          sudo apt-get install -y $PACKAGES

          cd build
          cmake .. \
            "-DCMAKE_CXX_COMPILER=${GPP_NAME}" \
            "-DNO_X11=${NO_X11}" \
            "-DNO_WAYLAND=${NO_WAYLAND}" \
            "-DCMAKE_BUILD_TYPE=Debug"
          
          cmake --build . -j 2
          sudo cmake --install .
          export TMPDIR=/tmp
          bash ../tests/suite.sh
  test-macos-arm64-amd64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          brew install gcc
          cd build
          cmake .. -D CMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Debug
          cmake --build . -j 2
          cmake --install .
          bash ../tests/suite.sh
  test-windows-amd64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: bash
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Release -j 2
          echo $HOME
          export TMPDIR=/c/Users/runneradmin/AppData/Local/Temp
          cmake --install .
          #installs to C:/Program Files (x86)/Clipboard/bin/clipboard.exe
          #add to path
          export PATH=$PATH:/c/Program\ Files\ \(x86\)/Clipboard/bin
          bash ../tests/suite.sh