name: Installer Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-amd64:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
          sh install.sh
          export TMPDIR=/tmp
          bash tests/suite.sh
  macos-arm64-amd64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
          sh install.sh
          bash tests/suite.sh
  windows-amd64:
    strategy:
     matrix:
       windows: [2022, 2019]
     
    runs-on: windows-${{ matrix.windows }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        shell: powershell
        run: |
          Start-Process powershell -Verb runAs -ArgumentList '-Command "Set-ExecutionPolicy RemoteSigned"'
          (Invoke-WebRequest -UseBasicParsing https://github.com/Slackadays/Clipboard/raw/main/src/install.ps1).Content | powershell
          #restart powershell to get the new path
          Start-Process powershell -Verb runAs -ArgumentList '-Command bash tests/suite.sh'
  freebsd-amd64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@c3f0301d1cfe8e161d617aacecc38e1a9c2c1cb4
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
            sh install.sh
            #export TMPDIR=/tmp
            #bash tests/suite.sh
  openbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@c3f0301d1cfe8e161d617aacecc38e1a9c2c1cb4
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.2'
          shell: bash
          run: |
            curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
            sh install.sh
            #export TMPDIR=/tmp
            #bash tests/suite.sh
  openbsd-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@c3f0301d1cfe8e161d617aacecc38e1a9c2c1cb4
        with:
          operating_system: openbsd
          architecture: arm64
          version: '7.2'
          shell: bash
          run: |
            curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
            sh install.sh
            #export TMPDIR=/tmp
            #bash tests/suite.sh
  netbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@cc6f40829d8f441a0e271d357353f3f3e15d5ccd
        with:
          operating_system: netbsd
          architecture: x86_64
          version: '9.2'
          shell: bash
          run: |
            curl -sSLk https://github.com/Slackadays/Clipboard/raw/main/src/install.sh > install.sh
            sh install.sh
            #export TMPDIR=/tmp
            #bash tests/suite.sh